# Generated by Django 2.2.2 on 2019-07-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('name_cuenta', models.CharField(help_text='Ingresa el nombre de la cuenta.', max_length=50, verbose_name='Cuenta')),
                ('description_cuenta', models.TextField(default='Agrega una descripción a tu cuenta.', help_text='Tomate tu tiempo e ingresa una buena descripción', max_length=500, null=True, verbose_name='Descripción de la cuenta')),
                ('status_cuenta', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, help_text='Ingrese un estado para la cuenta.', verbose_name='Estado')),
                ('date_since', models.DateTimeField(help_text='Ingrese la fecha de actividad para la cuenta.', verbose_name='Fecha de Actividad.')),
                ('date_until', models.DateTimeField(help_text='Ingrese la fecha de inactividad para la cuenta.', null=True, verbose_name='Fecha de Inactividad')),
                ('logo_cuenta', models.ImageField(height_field=50, upload_to='', verbose_name='Imagen', width_field=50)),
            ],
        ),
    ]
