# Generated by Django 2.2.2 on 2019-07-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eq_datascience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='logo_cuenta',
        ),
    ]
