# Generated by Django 2.2.4 on 2019-08-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eq_datascience', '0004_salesaccounttrimester_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='date_since',
            field=models.DateTimeField(blank=True, help_text='Ingrese la fecha de actividad para la cuenta.', null=True, verbose_name='Fecha de Actividad.'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='status_cuenta',
            field=models.BooleanField(blank=True, choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, help_text='Ingrese un estado para la cuenta.', null=True, verbose_name='Estado'),
        ),
    ]
